<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class OpenDataSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //
        DB::table('open_data_dataset')->truncate();
        DB::table('open_data_article')->truncate();
        DB::table('open_data_dataset')->insert([
            [
                'title' => 'Data Penduduk 2025',
                'description' => 'Dataset jumlah penduduk berdasarkan kecamatan',
                'category' => 'Demografi',
                'source_agency' => 'BPS',
                'dataset_url' => 'https://data.go.id/dataset/penduduk-2025',
                'published_at' => now()->subDays(rand(1, 365)),
                'created_at' => now(),
            ],
            [
                'title' => 'Data Kemiskinan 2024',
                'description' => 'Statistik tingkat kemiskinan nasional',
                'category' => 'Ekonomi',
                'source_agency' => 'BPS',
                'dataset_url' => 'https://data.go.id/dataset/kemiskinan-2024',
                'published_at' => now()->subDays(rand(1, 365)),
                'created_at' => now(),
            ],
            [
                'title' => 'Data Sekolah Indonesia',
                'description' => 'Daftar sekolah SD hingga SMA',
                'category' => 'Pendidikan',
                'source_agency' => 'Kemendikbud',
                'dataset_url' => 'https://data.go.id/dataset/sekolah',
                'published_at' => now()->subDays(rand(1, 365)),
                'created_at' => now(),
            ],
            [
                'title' => 'Data Rumah Sakit',
                'description' => 'Daftar rumah sakit seluruh Indonesia',
                'category' => 'Kesehatan',
                'source_agency' => 'Kemenkes',
                'dataset_url' => 'https://data.go.id/dataset/rumah-sakit',
                'published_at' => now()->subDays(rand(1, 365)),
                'created_at' => now(),
            ],
            [
                'title' => 'Data Curah Hujan',
                'description' => 'Informasi curah hujan bulanan',
                'category' => 'Lingkungan',
                'source_agency' => 'BMKG',
                'dataset_url' => 'https://data.go.id/dataset/curah-hujan',
                'published_at' => now()->subDays(rand(1, 365)),
                'created_at' => now(),
            ],
            [
                'title' => 'Data Transportasi Umum',
                'description' => 'Rute dan jadwal transportasi umum',
                'category' => 'Transportasi',
                'source_agency' => 'Dishub',
                'dataset_url' => 'https://data.go.id/dataset/transportasi',
                'published_at' => now()->subDays(rand(1, 365)),
                'created_at' => now(),
            ],
            [
                'title' => 'Data UMKM',
                'description' => 'Daftar UMKM aktif',
                'category' => 'Ekonomi',
                'source_agency' => 'Kemenkop UKM',
                'dataset_url' => 'https://data.go.id/dataset/umkm',
                'published_at' => now()->subDays(rand(1, 365)),
                'created_at' => now(),
            ],
            [
                'title' => 'Data Pariwisata',
                'description' => 'Destinasi wisata nasional',
                'category' => 'Pariwisata',
                'source_agency' => 'Kemenparekraf',
                'dataset_url' => 'https://data.go.id/dataset/pariwisata',
                'published_at' => now()->subDays(rand(1, 365)),
                'created_at' => now(),
            ],
            [
                'title' => 'Data Jalan Nasional',
                'description' => 'Data panjang jalan nasional',
                'category' => 'Infrastruktur',
                'source_agency' => 'Kementerian PUPR',
                'dataset_url' => 'https://data.go.id/dataset/jalan',
                'published_at' => now()->subDays(rand(1, 365)),
                'created_at' => now(),
            ],
            [
                'title' => 'Data Energi',
                'description' => 'Konsumsi energi nasional',
                'category' => 'Energi',
                'source_agency' => 'ESDM',
                'dataset_url' => 'https://data.go.id/dataset/energi',
                'published_at' => now()->subDays(rand(1, 365)),
                'created_at' => now(),
            ],
            [
                'title' => 'Data Harga Pangan',
                'description' => 'Harga bahan pokok harian',
                'category' => 'Ekonomi',
                'source_agency' => 'Kemendag',
                'dataset_url' => 'https://data.go.id/dataset/harga-pangan',
                'published_at' => now()->subDays(rand(1, 365)),
                'created_at' => now(),
            ],
            [
                'title' => 'Data Ketenagakerjaan',
                'description' => 'Statistik tenaga kerja',
                'category' => 'Sosial',
                'source_agency' => 'BPS',
                'dataset_url' => 'https://data.go.id/dataset/tenaga-kerja',
                'published_at' => now()->subDays(rand(1, 365)),
                'created_at' => now(),
            ],
            [
                'title' => 'Data Perikanan',
                'description' => 'Produksi hasil perikanan',
                'category' => 'Kelautan',
                'source_agency' => 'KKP',
                'dataset_url' => 'https://data.go.id/dataset/perikanan',
                'published_at' => now()->subDays(rand(1, 365)),
                'created_at' => now(),
            ],
            [
                'title' => 'Data Pertanian',
                'description' => 'Produksi pertanian nasional',
                'category' => 'Pertanian',
                'source_agency' => 'Kementan',
                'dataset_url' => 'https://data.go.id/dataset/pertanian',
                'published_at' => now()->subDays(rand(1, 365)),
                'created_at' => now(),
            ],
            [
                'title' => 'Data Keuangan Daerah',
                'description' => 'APBD per provinsi',
                'category' => 'Keuangan',
                'source_agency' => 'Kemenkeu',
                'dataset_url' => 'https://data.go.id/dataset/apbd',
                'published_at' => now()->subDays(rand(1, 365)),
                'created_at' => now(),
            ],
            [
                'title' => 'Data Kriminalitas',
                'description' => 'Statistik kriminalitas tahunan',
                'category' => 'Keamanan',
                'source_agency' => 'Polri',
                'dataset_url' => 'https://data.go.id/dataset/kriminalitas',
                'published_at' => now()->subDays(rand(1, 365)),
                'created_at' => now(),
            ],
            [
                'title' => 'Data Internet',
                'description' => 'Pengguna internet di Indonesia',
                'category' => 'Teknologi',
                'source_agency' => 'Kominfo',
                'dataset_url' => 'https://data.go.id/dataset/internet',
                'published_at' => now()->subDays(rand(1, 365)),
                'created_at' => now(),
            ],
            [
                'title' => 'Data Industri',
                'description' => 'Statistik industri manufaktur',
                'category' => 'Industri',
                'source_agency' => 'Kemenperin',
                'dataset_url' => 'https://data.go.id/dataset/industri',
                'published_at' => now()->subDays(rand(1, 365)),
                'created_at' => now(),
            ],
            [
                'title' => 'Data Ekspor Impor',
                'description' => 'Statistik perdagangan luar negeri',
                'category' => 'Perdagangan',
                'source_agency' => 'BPS',
                'dataset_url' => 'https://data.go.id/dataset/ekspor-impor',
                'published_at' => now()->subDays(rand(1, 365)),
                'created_at' => now(),
            ],
            [
                'title' => 'Data Lingkungan Hidup',
                'description' => 'Indeks kualitas lingkungan',
                'category' => 'Lingkungan',
                'source_agency' => 'KLHK',
                'dataset_url' => 'https://data.go.id/dataset/lingkungan',
                'published_at' => now()->subDays(rand(1, 365)),
                'created_at' => now(),
            ],
        ]);
        DB::table('open_data_article')->insert([
            [
                'title' => 'Perkembangan Data Terbuka di Indonesia',
                'content' => 'Data terbuka menjadi salah satu pilar transparansi pemerintah yang terus berkembang.',
                'author' => 'Admin',
                'article_url' => 'https://data.go.id/article/perkembangan-open-data',
                'published_at' => now()->subDays(rand(1, 365)),
                'created_at' => now(),
            ],
            [
                'title' => 'Manfaat Open Data untuk Masyarakat',
                'content' => 'Open data memberikan akses informasi publik yang dapat dimanfaatkan untuk berbagai kebutuhan.',
                'author' => 'Ivan',
                'article_url' => 'https://data.go.id/article/manfaat-open-data',
                'published_at' => now()->subDays(rand(1, 365)),
                'created_at' => now(),
            ],
            [
                'title' => 'Peran BPS dalam Penyediaan Data',
                'content' => 'BPS menyediakan berbagai dataset statistik resmi untuk publik.',
                'author' => 'Admin',
                'article_url' => 'https://data.go.id/article/peran-bps',
                'published_at' => now()->subDays(rand(1, 365)),
                'created_at' => now(),
            ],
            [
                'title' => 'Transformasi Digital Pemerintah',
                'content' => 'Digitalisasi layanan publik meningkatkan efisiensi dan transparansi.',
                'author' => 'Editor',
                'article_url' => 'https://data.go.id/article/transformasi-digital',
                'published_at' => now()->subDays(rand(1, 365)),
                'created_at' => now(),
            ],
            [
                'title' => 'Data Kesehatan Nasional',
                'content' => 'Dataset kesehatan membantu dalam pengambilan kebijakan berbasis data.',
                'author' => 'Admin',
                'article_url' => 'https://data.go.id/article/data-kesehatan',
                'published_at' => now()->subDays(rand(1, 365)),
                'created_at' => now(),
            ],
            [
                'title' => 'Analisis Data Pendidikan',
                'content' => 'Data pendidikan dapat digunakan untuk meningkatkan kualitas pembelajaran.',
                'author' => 'Ivan',
                'article_url' => 'https://data.go.id/article/data-pendidikan',
                'published_at' => now()->subDays(rand(1, 365)),
                'created_at' => now(),
            ],
            [
                'title' => 'Penggunaan Data untuk Startup',
                'content' => 'Startup memanfaatkan open data untuk inovasi produk.',
                'author' => 'Guest',
                'article_url' => 'https://data.go.id/article/data-startup',
                'published_at' => now()->subDays(rand(1, 365)),
                'created_at' => now(),
            ],
            [
                'title' => 'Tren Big Data di Indonesia',
                'content' => 'Big data menjadi tren dalam pengolahan informasi skala besar.',
                'author' => 'Editor',
                'article_url' => 'https://data.go.id/article/big-data',
                'published_at' => now()->subDays(rand(1, 365)),
                'created_at' => now(),
            ],
            [
                'title' => 'Data Transportasi Publik',
                'content' => 'Informasi transportasi membantu mobilitas masyarakat.',
                'author' => 'Admin',
                'article_url' => 'https://data.go.id/article/transportasi',
                'published_at' => now()->subDays(rand(1, 365)),
                'created_at' => now(),
            ],
            [
                'title' => 'Open Data dan Smart City',
                'content' => 'Smart city memanfaatkan data untuk pengelolaan kota yang lebih baik.',
                'author' => 'Ivan',
                'article_url' => 'https://data.go.id/article/smart-city',
                'published_at' => now()->subDays(rand(1, 365)),
                'created_at' => now(),
            ],
            [
                'title' => 'Keamanan Data Publik',
                'content' => 'Perlindungan data menjadi isu penting dalam open data.',
                'author' => 'Admin',
                'article_url' => 'https://data.go.id/article/keamanan-data',
                'published_at' => now()->subDays(rand(1, 365)),
                'created_at' => now(),
            ],
            [
                'title' => 'Data Lingkungan Hidup',
                'content' => 'Dataset lingkungan digunakan untuk menjaga kelestarian alam.',
                'author' => 'Editor',
                'article_url' => 'https://data.go.id/article/lingkungan',
                'published_at' => now()->subDays(rand(1, 365)),
                'created_at' => now(),
            ],
            [
                'title' => 'Pemanfaatan API Data',
                'content' => 'API memudahkan integrasi data antar sistem.',
                'author' => 'Ivan',
                'article_url' => 'https://data.go.id/article/api-data',
                'published_at' => now()->subDays(rand(1, 365)),
                'created_at' => now(),
            ],
            [
                'title' => 'Open Government Data',
                'content' => 'Pemerintah membuka akses data untuk transparansi.',
                'author' => 'Guest',
                'article_url' => 'https://data.go.id/article/open-government',
                'published_at' => now()->subDays(rand(1, 365)),
                'created_at' => now(),
            ],
            [
                'title' => 'Data Ekonomi Digital',
                'content' => 'Ekonomi digital berkembang pesat dengan dukungan data.',
                'author' => 'Admin',
                'article_url' => 'https://data.go.id/article/ekonomi-digital',
                'published_at' => now()->subDays(rand(1, 365)),
                'created_at' => now(),
            ],
            [
                'title' => 'Visualisasi Data',
                'content' => 'Visualisasi membantu memahami data secara lebih mudah.',
                'author' => 'Editor',
                'article_url' => 'https://data.go.id/article/visualisasi',
                'published_at' => now()->subDays(rand(1, 365)),
                'created_at' => now(),
            ],
            [
                'title' => 'Machine Learning dan Data',
                'content' => 'Machine learning membutuhkan data dalam jumlah besar.',
                'author' => 'Ivan',
                'article_url' => 'https://data.go.id/article/machine-learning',
                'published_at' => now()->subDays(rand(1, 365)),
                'created_at' => now(),
            ],
            [
                'title' => 'Integrasi Sistem Informasi',
                'content' => 'Integrasi sistem mempermudah pengelolaan data.',
                'author' => 'Admin',
                'article_url' => 'https://data.go.id/article/integrasi-sistem',
                'published_at' => now()->subDays(rand(1, 365)),
                'created_at' => now(),
            ],
            [
                'title' => 'Kebijakan Satu Data Indonesia',
                'content' => 'Program Satu Data Indonesia meningkatkan kualitas data pemerintah.',
                'author' => 'Guest',
                'article_url' => 'https://data.go.id/article/satu-data',
                'published_at' => now()->subDays(rand(1, 365)),
                'created_at' => now(),
            ],
            [
                'title' => 'Masa Depan Open Data',
                'content' => 'Open data akan terus berkembang seiring kemajuan teknologi.',
                'author' => 'Editor',
                'article_url' => 'https://data.go.id/article/masa-depan',
                'published_at' => now()->subDays(rand(1, 365)),
                'created_at' => now(),
            ],
        ]);
    }
}
