version: '3.8'

services:
  app:
    build: .
    container_name: majadiddy_backend
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    ports:
      - "8000:8000"

  postgres:
    image: postgres:16
    container_name: majadiddy_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: majadiddy
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: